mongoimport --collection=motivationsTest --db=moov --file="c:\\dev\\data\\MoovDB\\motivationsTest.json"
mongoimport --collection=locale_en --db=moov --file="c:\\dev\\data\\MoovDB\\locale_en.json"
mongoimport --collection=locale_he_ma --db=moov --file="c:\\dev\\data\\MoovDB\\locale_he_ma.json"
mongoimport --collection=locale_he_fe --db=moov --file="c:\\dev\\data\\MoovDB\\locale_he_fe.json"
mongoimport --collection=users --db=moov --file="c:\\dev\\data\\MoovDB\\users.json"
mongoimport --collection=questions --db=moov --file="c:\\dev\\data\\MoovDB\\questions.json"
